package app.lucys.lib.lucytheme.ui.atom.images

import androidx.annotation.DrawableRes
import app.lucys.lib.lucytheme.R

enum class LucyOutlineIcon(@DrawableRes val resourceId: Int) {
    Booking(R.drawable.icon_outline_booking),
    Delivery(R.drawable.icon_outline_delivery),
    EWallet(R.drawable.icon_outline_e_wallet),
    Queue(R.drawable.icon_outline_queue),
    Setting(R.drawable.icon_outline_setting),
    ActiveOrder(R.drawable.icon_outline_active_order),
    HistoryTransaction(R.drawable.icon_outline_history_transaction),
    Customer(R.drawable.icon_outline_customer),
    PayLater(R.drawable.icon_outline_paylater),

    // ORIGINAL ICON
    AcademicCap(R.drawable.outline_academic_cap),
    Adjustment(R.drawable.outline_adjustments),
    Annotation(R.drawable.outline_annotation),
    Archive(R.drawable.outline_archive),
    ArrowCircleDown(R.drawable.outline_arrow_circle_down),
    ArrowCircleLeft(R.drawable.outline_arrow_circle_left),
    ArrowCircleRight(R.drawable.outline_arrow_circle_right),
    ArrowCircleUp(R.drawable.outline_arrow_circle_up),
    ArrowDown(R.drawable.outline_arrow_down),
    ArrowLeft(R.drawable.outline_arrow_left),
    ArrowRight(R.drawable.outline_arrow_right),
    ArrowUp(R.drawable.outline_arrow_up),
    ArrowNarrowDown(R.drawable.outline_arrow_narrow_down),
    ArrowNarrowLeft(R.drawable.outline_arrow_narrow_left),
    ArrowNarrowRight(R.drawable.outline_arrow_narrow_right),
    ArrowNarrowUp(R.drawable.outline_arrow_narrow_up),
    ArrowSmallDown(R.drawable.outline_arrow_sm_down),
    ArrowSmallLeft(R.drawable.outline_arrow_sm_left),
    ArrowSmallRight(R.drawable.outline_arrow_sm_right),
    ArrowSmallUp(R.drawable.outline_arrow_sm_up),
    ArrowsExpand(R.drawable.outline_arrows_expand),
    AtSymbol(R.drawable.outline_at_symbol),

    Backspace(R.drawable.outline_backspace),
    BadgeCheck(R.drawable.outline_badge_check),
    Beaker(R.drawable.outline_beaker),
    Bell(R.drawable.outline_bell),
    BookOpen(R.drawable.outline_book_open),
    Bookmark(R.drawable.outline_bookmark),
    BookmarkAlt(R.drawable.outline_bookmark_alt),
    BranchPass(R.drawable.outline_branch_pass),
    Briefcase(R.drawable.outline_briefcase),

    Cake(R.drawable.outline_cake),
    Calendar(R.drawable.outline_calendar),
    Camera(R.drawable.outline_camera),
    Cash(R.drawable.outline_cash),
    ChartBar(R.drawable.outline_chart_bar),
    ChartPie(R.drawable.outline_chart_pie),
    ChartSquareBar(R.drawable.outline_chart_square_bar),
    Chat(R.drawable.outline_chat),
    ChatAlt(R.drawable.outline_chat_alt),
    ChatAlt2(R.drawable.outline_chat_alt_2),
    Check(R.drawable.outline_check),
    CheckCircle(R.drawable.outline_check_circle),
    ChevronDoubleDown(R.drawable.outline_chevron_double_down),
    ChevronDoubleLeft(R.drawable.outline_chevron_double_left),
    ChevronDoubleRight(R.drawable.outline_chevron_double_right),
    ChevronDoubleUp(R.drawable.outline_chevron_double_up),
    ChevronDown(R.drawable.outline_chevron_down),
    ChevronLeft(R.drawable.outline_chevron_left),
    ChevronRight(R.drawable.outline_chevron_right),
    ChevronUp(R.drawable.outline_chevron_up),
    Chip(R.drawable.outline_chip),
    ClipboardCheck(R.drawable.outline_clipboard_check),
    ClipboardCopy(R.drawable.outline_clipboard_copy),
    ClipboardList(R.drawable.outline_clipboard_list),
    Clock(R.drawable.outline_clock),
    Cloud(R.drawable.outline_cloud),
    CloudDownload(R.drawable.outline_cloud_download),
    CloudUpload(R.drawable.outline_cloud_upload),
    Code(R.drawable.outline_code),
    Collection(R.drawable.outline_collection),
    ColorSwatch(R.drawable.outline_color_swatch),
    CreditCard(R.drawable.outline_credit_card),
    Cube(R.drawable.outline_cube),
    CubeTransparent(R.drawable.outline_cube_transparent),
    CurrencyBangladeshi(R.drawable.outline_currency_bangladeshi),
    CurrencyDollar(R.drawable.outline_currency_dollar),
    CurrencyEuro(R.drawable.outline_currency_euro),
    CurrencyPound(R.drawable.outline_currency_pound),
    CurrencyRupee(R.drawable.outline_currency_rupee),
    CurrencyYen(R.drawable.outline_currency_yen),
    CursorClick(R.drawable.outline_cursor_click),

    Database(R.drawable.outline_database),
    DesktopComputer(R.drawable.outline_desktop_computer),
    DeviceMobile(R.drawable.outline_device_mobile),
    DineIn(R.drawable.outline_dine_in),
    Document(R.drawable.outline_document),
    DocumentAdd(R.drawable.outline_document_add),
    DocumentDownload(R.drawable.outline_document_download),
    DocumentDuplicate(R.drawable.outline_document_duplicate),
    DocumentRemove(R.drawable.outline_document_remove),
    DocumentReport(R.drawable.outline_document_report),
    DocumentSearch(R.drawable.outline_document_search),
    DocumentText(R.drawable.outline_document_text),
    DotsCircleHorizontal(R.drawable.outline_dots_circle_horizontal),
    DotsHorizontal(R.drawable.outline_dots_horizontal),
    DotsVertical(R.drawable.outline_dots_vertical),
    Download(R.drawable.outline_download),
    Duplicate(R.drawable.outline_duplicate),

    EmojiHappy(R.drawable.outline_emoji_happy),
    EmojiSad(R.drawable.outline_emoji_sad),
    Exclamation(R.drawable.outline_exclamation),
    ExclamationCircle(R.drawable.outline_exclamation_circle),
    ExternalLink(R.drawable.outline_external_link),
    Eye(R.drawable.outline_eye),
    EyeOff(R.drawable.outline_eye_off),
    FastForward(R.drawable.outline_fast_forward),
    Film(R.drawable.outline_film),
    Filter(R.drawable.outline_filter),
    FingerPrint(R.drawable.outline_finger_print),
    Fire(R.drawable.outline_fire),
    Flag(R.drawable.outline_flag),
    Folder(R.drawable.outline_folder),
    FolderAdd(R.drawable.outline_folder_add),
    FolderDownload(R.drawable.outline_folder_download),
    FolderOpen(R.drawable.outline_folder_open),
    FolderRemove(R.drawable.outline_folder_remove),
    Gift(R.drawable.outline_gift),
    Globe(R.drawable.outline_globe),
    GlobeAlt(R.drawable.outline_globe_alt),
    Hand(R.drawable.outline_hand),
    Hashtag(R.drawable.outline_hashtag),
    Heart(R.drawable.outline_heart),
    Home(R.drawable.outline_home),

    Identification(R.drawable.outline_identification),
    IdentificationAlt(R.drawable.outline_identification_1),
    Inbox(R.drawable.outline_inbox),
    InboxIn(R.drawable.outline_inbox_in),
    InformationCircle(R.drawable.outline_information_circle),

    LightBulb(R.drawable.outline_light_bulb),
    LightningBolt(R.drawable.outline_lightning_bolt),
    Link(R.drawable.outline_link),
    LocationMarker(R.drawable.outline_location_marker),
    LockClosed(R.drawable.outline_lock_closed),
    LockOpen(R.drawable.outline_lock_open),
    Logout(R.drawable.outline_logout),
    LogoutAlt(R.drawable.outline_logout_1),

    Mail(R.drawable.outline_mail),
    MailOpen(R.drawable.outline_mail_open),
    Menu(R.drawable.outline_menu),
    MenuAlt1(R.drawable.outline_menu_alt_1),
    MenuAlt2(R.drawable.outline_menu_alt_2),
    MenuAlt3(R.drawable.outline_menu_alt_3),
    MenuAlt4(R.drawable.outline_menu_alt_4),
    Microphone(R.drawable.outline_microphone),
    Minus(R.drawable.outline_minus),
    MinusCircle(R.drawable.outline_minus_circle),
    MinusSmall(R.drawable.outline_minus_sm),
    Moon(R.drawable.outline_moon),
    MusicNote(R.drawable.outline_music_note),

    Newspaper(R.drawable.outline_newspaper),

    OfficeBuilding(R.drawable.outline_office_building),

    PaperAirplane(R.drawable.outline_paper_airplane),
    PaperClip(R.drawable.outline_paper_clip),
    Pause(R.drawable.outline_pause),
    Pencil(R.drawable.outline_pencil),
    PencilAlt(R.drawable.outline_pencil_alt),
    Phone(R.drawable.outline_phone),
    PhoneIncoming(R.drawable.outline_phone_incoming),
    PhoneMissedCall(R.drawable.outline_phone_missed_call),
    PhoneOutgoing(R.drawable.outline_phone_outgoing),
    Photograph(R.drawable.outline_photograph),
    Play(R.drawable.outline_play),
    Plus(R.drawable.outline_plus),
    PlusCircle(R.drawable.outline_plus_circle),
    PlusSmall(R.drawable.outline_plus_sm),
    PresentationChartBar(R.drawable.outline_presentation_chart_bar),
    PresentationChartLine(R.drawable.outline_presentation_chart_line),
    Printer(R.drawable.outline_printer),
    Puzzle(R.drawable.outline_puzzle),

    QrCode(R.drawable.outline_qrcode),
    QuestionMarkCircle(R.drawable.outline_question_mark_circle),
    QuickOrder(R.drawable.outline_quick_order),

    ReceiptRefund(R.drawable.outline_receipt_refund),
    ReceiptTax(R.drawable.outline_receipt_tax),
    Refresh(R.drawable.outline_refresh),
    Reply(R.drawable.outline_reply),
    Reservation(R.drawable.outline_reservation),
    Rewind(R.drawable.outline_rewind),
    RSS(R.drawable.outline_rss),

    Save(R.drawable.outline_save),
    SaveAs(R.drawable.outline_save_as),
    Scale(R.drawable.outline_scale),
    Scissors(R.drawable.outline_scissors),
    Search(R.drawable.outline_search),
    SearchCircle(R.drawable.outline_search_circle),
    Selector(R.drawable.outline_selector),
    Server(R.drawable.outline_server),
    Share(R.drawable.outline_share),
    ShieldCheck(R.drawable.outline_shield_check),
    ShieldExclamation(R.drawable.outline_shield_exclamation),
    ShoppingBag(R.drawable.outline_shopping_bag),
    SortAscending(R.drawable.outline_sort_ascending),
    SortDescending(R.drawable.outline_sort_descending),
    Sparkles(R.drawable.outline_sparkles),
    SpeakerPhone(R.drawable.outline_speakerphone),
    Star(R.drawable.outline_star),
    StatusOffline(R.drawable.outline_status_offline),
    StatusOnline(R.drawable.outline_status_online),
    Stop(R.drawable.outline_stop),
    Store(R.drawable.outline_store),
    Support(R.drawable.outline_support),
    SwitchHorizontal(R.drawable.outline_switch_horizontal),
    SwitchVertical(R.drawable.outline_switch_vertical),

    Table(R.drawable.outline_table),
    Takeaway(R.drawable.outline_takeaway),
    Template(R.drawable.outline_template),
    Terminal(R.drawable.outline_terminal),
    ThumbDown(R.drawable.outline_thumb_down),
    ThumbUp(R.drawable.outline_thumb_up),
    Ticket(R.drawable.outline_ticket),
    Translate(R.drawable.outline_translate),
    Trash(R.drawable.outline_trash),
    TrendingDown(R.drawable.outline_trending_down),
    TrendingUp(R.drawable.outline_trending_up),
    Truck(R.drawable.outline_truck),

    Upload(R.drawable.outline_upload),
    User(R.drawable.outline_user),
    UserAdd(R.drawable.outline_user_add),
    UserCircle(R.drawable.outline_user_circle),
    UserGroup(R.drawable.outline_user_group),
    Users(R.drawable.outline_users),

    Variable(R.drawable.outline_variable),
    VideoCamera(R.drawable.outline_video_camera),
    ViewBoards(R.drawable.outline_view_boards),
    ViewGrid(R.drawable.outline_view_grid),
    ViewList(R.drawable.outline_view_list),
    VolumeOff(R.drawable.outline_volume_off),
    VolumeUp(R.drawable.outline_volume_up),

    Wifi(R.drawable.outline_wifi),

    X(R.drawable.outline_x),
    XCircle(R.drawable.outline_x_circle),

    ZoomIn(R.drawable.outline_zoom_in),
    ZoomOut(R.drawable.outline_zoom_out),

    Lock(R.drawable.icon_outline_lock_closed),
}