package app.lucys.lib.lucytheme.ui.atom.images

import androidx.annotation.DrawableRes
import app.lucys.lib.lucytheme.R

enum class LucyFilledIcon(@DrawableRes val resourceId: Int) {
    Booking(R.drawable.icon_filled_booking),
    Delivery(R.drawable.icon_filled_delivery),
    Queue(R.drawable.icon_filled_queue),
    ActiveOrder(R.drawable.icon_filled_active_order),
    HistoryTransaction(R.drawable.icon_filled_history_transaction),
    Customer(R.drawable.icon_filled_customer),
    Logo(R.drawable.drawable_lucy_logo_small),
    PayLater(R.drawable.icon_filled_paylater),

    Clear(R.drawable.icon_filled_x_circle),
    Lock(R.drawable.icon_filled_lock_closed),

    // ORIGINAL ICONS
    AcademicCap(R.drawable.fill_academic_cap),
    Adjustment(R.drawable.fill_adjustments),
    Annotation(R.drawable.fill_annotation),
    Archive(R.drawable.fill_archive),
    ArrowCircleDown(R.drawable.fill_arrow_circle_down),
    ArrowCircleLeft(R.drawable.fill_arrow_circle_left),
    ArrowCircleRight(R.drawable.fill_arrow_circle_right),
    ArrowCircleUp(R.drawable.fill_arrow_circle_up),
    ArrowDown(R.drawable.fill_arrow_down),
    ArrowLeft(R.drawable.fill_arrow_left),
    ArrowRight(R.drawable.fill_arrow_right),
    ArrowUp(R.drawable.fill_arrow_up),
    ArrowNarrowDown(R.drawable.fill_arrow_narrow_down),
    ArrowNarrowLeft(R.drawable.fill_arrow_narrow_left),
    ArrowNarrowRight(R.drawable.fill_arrow_narrow_right),
    ArrowNarrowUp(R.drawable.fill_arrow_narrow_up),
    ArrowSmallDown(R.drawable.fill_arrow_sm_down),
    ArrowSmallLeft(R.drawable.fill_arrow_sm_left),
    ArrowSmallRight(R.drawable.fill_arrow_sm_right),
    ArrowSmallUp(R.drawable.fill_arrow_sm_up),
    ArrowsExpand(R.drawable.fill_arrows_expand),
    AtSymbol(R.drawable.fill_at_symbol),

    Backspace(R.drawable.fill_backspace),
    BadgeCheck(R.drawable.fill_badge_check),
    Beaker(R.drawable.fill_beaker),
    Bell(R.drawable.fill_bell),
    BookOpen(R.drawable.fill_book_open),
    Bookmark(R.drawable.fill_bookmark),
    BookmarkAlt(R.drawable.fill_bookmark_alt),
    BranchPass(R.drawable.fill_branch_pass),
    Briefcase(R.drawable.fill_briefcase),

    Cake(R.drawable.fill_cake),
    Calendar(R.drawable.fill_calendar),
    Camera(R.drawable.fill_camera),
    Cash(R.drawable.fill_cash),
    ChartBar(R.drawable.fill_chart_bar),
    ChartPie(R.drawable.fill_chart_pie),
    ChartSquareBar(R.drawable.fill_chart_square_bar),
    Chat(R.drawable.fill_chat),
    ChatAlt(R.drawable.fill_chat_alt),
    ChatAlt2(R.drawable.fill_chat_alt_2),
    Check(R.drawable.fill_check),
    CheckCircle(R.drawable.fill_check_circle),
    ChevronDoubleDown(R.drawable.fill_chevron_double_down),
    ChevronDoubleLeft(R.drawable.fill_chevron_double_left),
    ChevronDoubleRight(R.drawable.fill_chevron_double_right),
    ChevronDoubleUp(R.drawable.fill_chevron_double_up),
    ChevronDown(R.drawable.fill_chevron_down),
    ChevronLeft(R.drawable.fill_chevron_left),
    ChevronRight(R.drawable.fill_chevron_right),
    ChevronUp(R.drawable.fill_chevron_up),
    Chip(R.drawable.fill_chip),
    ClipboardCheck(R.drawable.fill_clipboard_check),
    ClipboardCopy(R.drawable.fill_clipboard_copy),
    ClipboardList(R.drawable.fill_clipboard_list),
    Clock(R.drawable.fill_clock),
    Cloud(R.drawable.fill_cloud),
    CloudDownload(R.drawable.fill_cloud_download),
    CloudUpload(R.drawable.fill_cloud_upload),
    Code(R.drawable.fill_code),
    Collection(R.drawable.fill_collection),
    ColorSwatch(R.drawable.fill_color_swatch),
    CreditCard(R.drawable.fill_credit_card),
    Cube(R.drawable.fill_cube),
    CubeTransparent(R.drawable.fill_cube_transparent),
    CurrencyBangladeshi(R.drawable.fill_currency_bangladeshi),
    CurrencyDollar(R.drawable.fill_currency_dollar),
    CurrencyEuro(R.drawable.fill_currency_euro),
    CurrencyPound(R.drawable.fill_currency_pound),
    CurrencyRupee(R.drawable.fill_currency_rupee),
    CurrencyYen(R.drawable.fill_currency_yen),
    CursorClick(R.drawable.fill_cursor_click),

    Database(R.drawable.fill_database),
    DesktopComputer(R.drawable.fill_desktop_computer),
    DeviceMobile(R.drawable.fill_device_mobile),
    DineIn(R.drawable.fill_dine_in),
    Document(R.drawable.fill_document),
    DocumentAdd(R.drawable.fill_document_add),
    DocumentDownload(R.drawable.fill_document_download),
    DocumentDuplicate(R.drawable.fill_document_duplicate),
    DocumentRemove(R.drawable.fill_document_remove),
    DocumentReport(R.drawable.fill_document_report),
    DocumentSearch(R.drawable.fill_document_search),
    DocumentText(R.drawable.fill_document_text),
    DotsCircleHorizontal(R.drawable.fill_dots_circle_horizontal),
    DotsHorizontal(R.drawable.fill_dots_horizontal),
    DotsVertical(R.drawable.fill_dots_vertical),
    Download(R.drawable.fill_download),
    DownloadAlt(R.drawable.fill_download_1),
    Duplicate(R.drawable.fill_duplicate),

    EmojiHappy(R.drawable.fill_emoji_happy),
    EmojiSad(R.drawable.fill_emoji_sad),
    Exclamation(R.drawable.fill_exclamation),
    ExclamationCircle(R.drawable.fill_exclamation_circle),
    ExternalLink(R.drawable.fill_external_link),
    Eye(R.drawable.fill_eye),
    EyeOff(R.drawable.fill_eye_off),
    FastForward(R.drawable.fill_fast_forward),
    Film(R.drawable.fill_film),
    Filter(R.drawable.fill_filter),
    FingerPrint(R.drawable.fill_finger_print),
    Fire(R.drawable.fill_fire),
    Flag(R.drawable.fill_flag),
    Folder(R.drawable.fill_folder),
    FolderAdd(R.drawable.fill_folder_add),
    FolderDownload(R.drawable.fill_folder_download),
    FolderOpen(R.drawable.fill_folder_open),
    FolderRemove(R.drawable.fill_folder_remove),
    Gift(R.drawable.fill_gift),
    Globe(R.drawable.fill_globe),
    GlobeAlt(R.drawable.fill_globe_alt),
    Hand(R.drawable.fill_hand),
    Hashtag(R.drawable.fill_hashtag),
    Heart(R.drawable.fill_heart),
    Home(R.drawable.fill_home),

    IconCurrencyDollar(R.drawable.fill_icon_currency_dollar),
    Identification(R.drawable.fill_identification),
    IdentificationAlt(R.drawable.fill_identification_1),
    Inbox(R.drawable.fill_inbox),
    InboxIn(R.drawable.fill_inbox_in),
    InformationCircle(R.drawable.fill_information_circle),

    LightBulb(R.drawable.fill_light_bulb),
    LightningBolt(R.drawable.fill_lightning_bolt),
    Link(R.drawable.fill_link),
    LocationMarker(R.drawable.fill_location_marker),
    LockClosed(R.drawable.fill_lock_closed),
    LockOpen(R.drawable.fill_lock_open),
    Logout(R.drawable.fill_logout),
    LogoutAlt(R.drawable.fill_logout_1),

    Mail(R.drawable.fill_mail),
    MailAlt(R.drawable.fill_mail_1),
    MailOpen(R.drawable.fill_mail_open),
    MdLibrary(R.drawable.fill_md_library),
    Menu(R.drawable.fill_menu),
    MenuAlt1(R.drawable.fill_menu_alt_1),
    MenuAlt2(R.drawable.fill_menu_alt_2),
    MenuAlt3(R.drawable.fill_menu_alt_3),
    MenuAlt4(R.drawable.fill_menu_alt_4),
    Microphone(R.drawable.fill_microphone),
    Minus(R.drawable.fill_minus),
    MinusCircle(R.drawable.fill_minus_circle),
    MinusSmall(R.drawable.fill_minus_sm),
    Moon(R.drawable.fill_moon),
    MusicNote(R.drawable.fill_music_note),

    Newspaper(R.drawable.fill_newspaper),

    OfficeBuilding(R.drawable.fill_office_building),

    PaperAirplane(R.drawable.fill_paper_airplane),
    PaperClip(R.drawable.fill_paper_clip),
    Pause(R.drawable.fill_pause),
    Pencil(R.drawable.fill_pencil),
    PencilAlt(R.drawable.fill_pencil_alt),
    Phone(R.drawable.fill_phone),
    PhoneIncoming(R.drawable.fill_phone_incoming),
    PhoneMissedCall(R.drawable.fill_phone_missed_call),
    PhoneOutgoing(R.drawable.fill_phone_outgoing),
    Photograph(R.drawable.fill_photograph),
    Play(R.drawable.fill_play),
    Plus(R.drawable.fill_plus),
    PlusCircle(R.drawable.fill_plus_circle),
    PlusSmall(R.drawable.fill_plus_sm),
    PresentationChartBar(R.drawable.fill_presentation_chart_bar),
    PresentationChartLine(R.drawable.fill_presentation_chart_line),
    Printer(R.drawable.fill_printer),
    Puzzle(R.drawable.fill_puzzle),

    QrCode(R.drawable.fill_qrcode),
    Qris(R.drawable.fill_qris),
    QuestionMarkCircle(R.drawable.fill_question_mark_circle),
    QuickOrder(R.drawable.fill_quick_order),

    ReceiptRefund(R.drawable.fill_receipt_refund),
    ReceiptTax(R.drawable.fill_receipt_tax),
    Refresh(R.drawable.fill_refresh),
    Reply(R.drawable.fill_reply),
    Reservation(R.drawable.fill_reservation),
    Rewind(R.drawable.fill_rewind),

    Save(R.drawable.fill_save),
    SaveAs(R.drawable.fill_save_as),
    Scale(R.drawable.fill_scale),
    Scissors(R.drawable.fill_scissors),
    Search(R.drawable.fill_search),
    SearchCircle(R.drawable.fill_search_circle),
    Selector(R.drawable.fill_selector),
    Server(R.drawable.fill_server),
    Share(R.drawable.fill_share),
    ShieldCheck(R.drawable.fill_shield_check),
    ShieldExclamation(R.drawable.fill_shield_exclamation),
    ShoppingBag(R.drawable.fill_shopping_bag),
    SortAscending(R.drawable.fill_sort_ascending),
    SortDescending(R.drawable.fill_sort_descending),
    Sparkles(R.drawable.fill_sparkles),
    SpeakerPhone(R.drawable.fill_speakerphone),
    SplitBill(R.drawable.fill_split_bill),
    Star(R.drawable.fill_star),
    StatusOffline(R.drawable.fill_status_offline),
    StatusOnline(R.drawable.fill_status_online),
    Stop(R.drawable.fill_stop),
    Store(R.drawable.fill_store),
    Support(R.drawable.fill_support),
    SwitchHorizontal(R.drawable.fill_switch_horizontal),
    SwitchVertical(R.drawable.fill_switch_vertical),

    Table(R.drawable.fill_table),
    TableAlt(R.drawable.fill_table_1),
    Takeaway(R.drawable.fill_takeaway),
    Template(R.drawable.fill_template),
    Terminal(R.drawable.fill_terminal),
    ThumbDown(R.drawable.fill_thumb_down),
    ThumbUp(R.drawable.fill_thumb_up),
    Ticket(R.drawable.fill_ticket),
    Translate(R.drawable.fill_translate),
    Trash(R.drawable.fill_trash),
    TrendingDown(R.drawable.fill_trending_down),
    TrendingUp(R.drawable.fill_trending_up),
    Truck(R.drawable.fill_truck),

    Upload(R.drawable.fill_upload),
    User(R.drawable.fill_user),
    UserAdd(R.drawable.fill_user_add),
    UserCircle(R.drawable.fill_user_circle),
    UserGroup(R.drawable.fill_user_group),
    UserRemove(R.drawable.fill_user_remove),
    Users(R.drawable.fill_users),

    Variable(R.drawable.fill_variable),
    VideoCamera(R.drawable.fill_video_camera),
    ViewBoards(R.drawable.fill_view_boards),
    ViewGrid(R.drawable.fill_view_grid),
    ViewGridAdd(R.drawable.fill_view_grid_add),
    ViewList(R.drawable.fill_view_list),
    VolumeOff(R.drawable.fill_volume_off),
    VolumeUp(R.drawable.fill_volume_up),

    Wifi(R.drawable.fill_wifi),

    X(R.drawable.fill_x),
    XCircle(R.drawable.fill_x_circle),

    ZoomIn(R.drawable.fill_zoom_in),
    ZoomOut(R.drawable.fill_zoom_out),
}